
FROM golang:latest



RUN go install golang.org/x/tools/gopls@latest
RUN go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
RUN go install github.com/ramya-rao-a/go-outline@latest
RUN go install honnef.co/go/tools/cmd/staticcheck@latest
RUN go install github.com/stamblerre/gocode@latest
RUN go install golang.org/x/tools/cmd/goimports@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest
